# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T15:34:10+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Batch(BaseModel):
    completed: Optional[bool] = None
    count: Optional[int] = None
    created_at: Optional[str] = None
    id: Optional[str] = None
    operation: Optional[str] = None
    results: Optional[List] = None
    status: Optional[str] = None


class Operation(Enum):
    whois = 'whois'
    check = 'check'


class Format(Enum):
    raw = 'raw'
    formatted = 'formatted'
    json = 'json'


class Options(BaseModel):
    format: Optional[Format] = None


class BatchPostRequest(BaseModel):
    domains: List[str] = Field(..., examples=[['foo.com', 'foo.net', 'foo.io']])
    operation: Operation
    options: Optional[Options] = None


class DbGetResponse(BaseModel):
    pass


class DomainsDomainCheckGetResponse(BaseModel):
    isAvailable: Optional[bool] = None


class DomainsDomainRankGetResponse(BaseModel):
    rank: Optional[float] = None


class ArrayOfBatch(BaseModel):
    batches: Optional[List[Batch]] = None
